# Generated by Django 5.2.1 on 2025-05-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('dealershipsk', models.AutoField(db_column='DealershipSK', primary_key=True, serialize=False, verbose_name='Dealership SK')),
                ('dealership_id', models.CharField(db_column='Dealership_ID', max_length=50, unique=True, verbose_name='Original Dealership ID')),
                ('dealername', models.CharField(db_column='DealerName', max_length=100, verbose_name='Dealer Name')),
                ('area', models.CharField(blank=True, db_column='Area', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Dealership',
                'verbose_name_plural': 'Dealerships',
                'db_table': 'Dealership',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DealershipContact',
            fields=[
                ('dealershipcontactsk', models.AutoField(db_column='DealershipContactSK', primary_key=True, serialize=False, verbose_name='Contact SK')),
                ('contactname', models.CharField(blank=True, db_column='ContactName', max_length=150, null=True, verbose_name='Contact Name')),
                ('role', models.CharField(blank=True, db_column='Role', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Dealership Contact',
                'verbose_name_plural': 'Dealership Contacts',
                'db_table': 'DealershipContact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureLookup',
            fields=[
                ('featuresk', models.AutoField(db_column='FeatureSK', primary_key=True, serialize=False, verbose_name='Feature SK')),
                ('featurename', models.CharField(db_column='FeatureName', max_length=150, unique=True, verbose_name='Feature Name')),
                ('featurecategory', models.CharField(blank=True, db_column='FeatureCategory', max_length=50, null=True, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Feature Lookup',
                'verbose_name_plural': 'Feature Lookups',
                'db_table': 'FeatureLookup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('salesordersk', models.AutoField(db_column='SalesOrderSK', primary_key=True, serialize=False, verbose_name='Sales Order SK')),
                ('salesorderno', models.CharField(blank=True, db_column='SalesOrderNo', max_length=50, null=True, unique=True, verbose_name='Sales Order No')),
                ('orderdate', models.DateField(blank=True, db_column='OrderDate', null=True, verbose_name='Order Date')),
                ('retaildate', models.DateField(blank=True, db_column='RetailDate', null=True, verbose_name='Retail Date')),
                ('pickupdate', models.DateField(blank=True, db_column='PickupDate', null=True, verbose_name='Pickup Date')),
                ('deliverydate', models.DateField(blank=True, db_column='DeliveryDate', null=True, verbose_name='Delivery Date')),
            ],
            options={
                'verbose_name': 'Sales Order',
                'verbose_name_plural': 'Sales Orders',
                'db_table': 'SalesOrder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusLookup',
            fields=[
                ('statussk', models.AutoField(db_column='StatusSK', primary_key=True, serialize=False, verbose_name='Status SK')),
                ('statuscode', models.CharField(db_column='StatusCode', max_length=10, unique=True, verbose_name='Status Code')),
                ('statustext', models.CharField(db_column='StatusText', max_length=255, verbose_name='Status Text')),
                ('statusgrouping', models.CharField(db_column='StatusGrouping', max_length=100, verbose_name='Status Grouping')),
                ('statussortorder', models.PositiveSmallIntegerField(db_column='StatusSortOrder', verbose_name='Sort Order')),
            ],
            options={
                'verbose_name': 'Status Lookup',
                'verbose_name_plural': 'Status Lookups',
                'db_table': 'StatusLookup',
                'ordering': ['statussortorder'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehiclesk', models.AutoField(db_column='VehicleSK', primary_key=True, serialize=False, verbose_name='Vehicle SK')),
                ('vin', models.CharField(blank=True, db_column='VIN', max_length=17, null=True, unique=True)),
                ('materialdesc_source', models.CharField(blank=True, db_column='MaterialDesc_Source', max_length=255, null=True, verbose_name='Source Material Desc')),
                ('modelname', models.CharField(blank=True, db_column='ModelName', help_text='Parsed by DB trigger', max_length=100, null=True)),
                ('bodystyle', models.CharField(blank=True, db_column='BodyStyle', help_text='Parsed by DB trigger', max_length=150, null=True)),
                ('seatconfiguration', models.CharField(blank=True, db_column='SeatConfiguration', help_text='Parsed by DB trigger', max_length=20, null=True)),
                ('modelyear', models.IntegerField(blank=True, db_column='ModelYear', help_text='Parsed by DB trigger (e.g., 2024)', null=True)),
                ('trimlevel', models.CharField(blank=True, db_column='TrimLevel', max_length=100, null=True, verbose_name='Trim Level')),
                ('plantcode', models.CharField(blank=True, db_column='PlantCode', max_length=10, null=True, verbose_name='Plant Code')),
                ('basemsrp', models.DecimalField(blank=True, db_column='BaseMSRP', decimal_places=2, max_digits=12, null=True, verbose_name='Base MSRP')),
                ('dealercost', models.DecimalField(blank=True, db_column='DealerCost', decimal_places=2, max_digits=12, null=True, verbose_name='Dealer Cost')),
                ('currentstatusdate', models.DateField(blank=True, db_column='CurrentStatusDate', null=True, verbose_name='Current Status Date')),
                ('stockcategory', models.CharField(blank=True, db_column='StockCategory', max_length=50, null=True, verbose_name='Stock Category')),
                ('stocktype', models.CharField(blank=True, db_column='StockType', max_length=20, null=True, verbose_name='Stock Type')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'Vehicle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectedoptionvalue', models.CharField(db_column='SelectedOptionValue', max_length=255, verbose_name='Selected Option')),
            ],
            options={
                'verbose_name': 'Vehicle Feature',
                'verbose_name_plural': 'Vehicle Features',
                'db_table': 'VehicleFeature',
                'managed': False,
            },
        ),
    ]
